import type { Metadata } from "next";
import "../../globals.css";
import BackgroundLayout from "@/components/layout/background";
import { ThemeProvider } from "@mui/material";
import theme from "@/lib/features/theme";
import NavBar from "@/components/navigation/navBar";
import SideBarProvider from "../SideBarProvider";
import SideMenu from "@/components/navigation/sideMenu";

export const metadata: Metadata = {
  title: "Space Tourism Website",
  description: "Generated by Devon Adams",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <SideBarProvider>
            <SideMenu />
            <BackgroundLayout>
              <>
                <NavBar />
                {children}
              </>
            </BackgroundLayout>
          </SideBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
